###################################
###       SNAKEFILE FAA         ###
###################################



#--------------#
#   ARTEMIAS   #
#--------------#

rule artemias:
    input:
        inferencia = "artemias/code/01inferencia_estadistica.R",
        visualizacion = "artemias/code/02visualizacion.R",
        pca = "artemias/code/03pca_faa.R",
        artemias_22 = "artemias/code/04artemias_2022.R",
        inferencia_tamhane = "artemias/code/05inferencia_estadistica.py"
    output:
        "artemias/results/plots/area_ag.png",
        "artemias/results/plots/normalidad_homocedasticidad.png",
        "artemias/results/plots/no_normles.png",
        "artemias/data/pca_artemias.png",
        "artemias/results/plots/rpca.png"
    conda:
        "FAA_env.yml"
    shell:
        """
        scripts=(
            {input.inferencia}
            {input.visualizacion}
            {input.pca}
            {input.artemias_22}
        )

        for script in ${{scripts[*]}}
        do
            Rscript $script
        done

        python {input.inferencia_tamhane}
        """

#--------------#
#   CONDUCTA   #
#--------------#

rule conducta:
    input:
        "conducta/code/conducta.R"
    output:
        "conducta/results/plots/om.png",
        "conducta/results/plots/hm.png",
        "conducta/results/plots/pm.png",
        "conducta/results/plots/obs_esp.png",
        "conducta/results/plots/pc_ratones.png",
        "conducta/results/plots/rca.png"
    conda:
        "FAA_env.yml"
    shell:
        """
        Rscript {input}
        """

#---------------#
#   TENEBRIOS   #
#---------------#

rule tenebrios:
    input:
        grupo = "tenebrios/code/01tenebrios.R",
        procesar_todos = "tenebrios/code/02procesar_data.sh",
        clase = "tenebrios/code/03t_todos_limpio.R" 
    output:
        png1 = "tenebrios/results/plots/masa_corporal_grupo.png",
        png2 = "tenebrios/results/plots/masa_corporal_tasa_crec_grupo.png",
        csv_process = "tenebrios/data/procesada/tenebrios_todos_process.csv",
        png4 = "tenebrios/results/plots/masa_corporal_todos.png",
        png5 = "tenebrios/results/plots/tasa_crecimiento_todos.png",
        png6 = "tenebrios/results/plots/comparacion_semanas_crecimeinto.png"
    conda:
        "FAA_env.yml"
    shell:
        """
        Rscript {input.grupo}

        bash {input.procesar_todos} > {output.csv_process}

        Rscript {input.clase} 
        """
#---------------#
#   EXPOSICIÓN  #
#---------------#

rule trabajo_exposicion:
    input:
        "trabajo_exposicion/code/Simulacion_endogamia.R"
    output:
        "trabajo_exposicion/results/tables/simulacion.csv",
        "trabajo_exposicion/results/plots/histogramas.png",
        "trabajo_exposicion/results/plots/endogamia.png",
        "trabajo_exposicion/results/plots/regresion.png"
    conda:
        "FAA_env.yml"
    shell:
        """
        Rscript {input}
        """
