
rule biometria:
    input:
        "code/01biometria.R"
    output:
        "results/plots/biometria/01dbh_altura.png",
        "results/plots/biometria/02hist_dbh.png"
    conda:
        "AFV_campo_env.yml"
    shell:
        """
        Rscript {input}
        """

rule eficiencia_fotosintetica:
    input:
        "code/02ef_fotos.R"
    output:
        "results/plots/eficiencia_fotosintetica/03PAR.png",
        "results/plots/eficiencia_fotosintetica/04Temperatura.png",
        "results/plots/eficiencia_fotosintetica/05fotosintesis.png",
        "results/plots/eficiencia_fotosintetica/06transpiracion.png",
        "results/plots/eficiencia_fotosintetica/07conductancia_estomatica.png",
        "results/plots/eficiencia_fotosintetica/08pca_ef_foto.png"
    conda:
        "AFV_campo_env.yml"
    shell:
        """
        Rscript {input}
        """

rule intercambio_gaseoso:
    input:
        "code/03inter_gas.R"
    output:
        "results/plots/intercambio_gaseoso/09T_vaselina_hojas_sol.png",
        "results/plots/intercambio_gaseoso/10T_vaselina_hojas_som.png",
        "results/plots/intercambio_gaseoso/11ef_foto_rosalillo.png"
    conda:
        "AFV_campo_env.yml"
    shell:
        """
        Rscript {input}
        """

rule microclima:
    input:
        "code/04microclima.R"
    output:
        "results/plots/microclima/12PAR_microclima.png",
        "results/plots/microclima/13Temp_microclima.png"
    conda:
        "AFV_campo_env.yml" 
    shell:
        """
        Rscript {input}
        """

rule pigmentos_polifenoles:
    input:
        "code/05pig_pol.R"
    output:
        "results/plots/pigmentos_polifenoles/14NBI.png",
        "results/plots/pigmentos_polifenoles/15clorofila.png",
        "results/plots/pigmentos_polifenoles/16flavonoides.png",
        "results/plots/pigmentos_polifenoles/17antocianinas.png",
        "results/plots/pigmentos_polifenoles/18pca_pigmentos_polifenoles.png",
        "results/plots/pigmentos_polifenoles/19NBI_hoja_rosalillo.png",
        "results/plots/pigmentos_polifenoles/20nivel_colorfilas.png",
        "results/plots/pigmentos_polifenoles/21flavos_hoja_rosalillo.png",
        "results/plots/pigmentos_polifenoles/22antos_hoja_rosalillo.png",
        "results/plots/pigmentos_polifenoles/23pca_pigmentos_fenoles.png"
    conda:
        "AFV_campo_env.yml"
    shell:
        """
        Rscript {input}
        """
